#!/bin/sh
# Wraps an OpenCL kernel source file into a C++ header holding it as a raw
# string literal.
#
#   usage: scripts/embed_kernel.sh <input.cl> <output.hpp>
#
# The interactive renderer used to read the .cl file at runtime from a path
# relative to the working directory, which only worked when launched from the
# repository root and would not survive installation. Baking the source into
# the binary removes the lookup entirely.

set -e

if [ $# -ne 2 ]; then
    echo "usage: $0 <input.cl> <output.hpp>" >&2
    exit 1
fi

IN="$1"
OUT="$2"

if [ ! -f "$IN" ]; then
    echo "$0: no such kernel source: $IN" >&2
    exit 1
fi

# The delimiter must not appear in the kernel source or the literal ends early.
if grep -q ')PARALLELBROT_CL' "$IN"; then
    echo "$0: kernel source contains the raw string delimiter" >&2
    exit 1
fi

mkdir -p "$(dirname "$OUT")"

{
    echo '// Generated by scripts/embed_kernel.sh — do not edit.'
    printf '// Source: %s\n' "$IN"
    echo '#ifndef PARALLELBROT_OPENCL_KERNEL_SOURCE_HPP'
    echo '#define PARALLELBROT_OPENCL_KERNEL_SOURCE_HPP'
    echo ''
    echo 'namespace parallelbrot {'
    echo ''
    echo 'inline const char* opencl_kernel_source() {'
    echo '    return R"PARALLELBROT_CL('
    cat "$IN"
    echo ')PARALLELBROT_CL";'
    echo '}'
    echo ''
    echo '}  // namespace parallelbrot'
    echo ''
    echo '#endif  // PARALLELBROT_OPENCL_KERNEL_SOURCE_HPP'
} > "$OUT"
